name: Publish

on:
  push:

jobs:
  build:
    name: Build Document
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Build
        run: make html
      #- name: Copy
      #  run: |
      #    mkdir -p ./public/feature-branch
      #    cp -rT ./_build/html ./public/feature-branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_buid/html
          destination_dir: feature-branch2
          keep_files: true
